language: node_js
node_js:
- 11.6.0
cache: npm

install:
 - npm ci

script: 
 - npm test
 - npm run build

script: | 
  curl -s -L https://detect.synopsys.com/detect.sh | bash -s - --blackduck.url="https://bdscan.daimler.com" \
   --blackduck.api.token="$HUB_TOKEN" \
   --detect.project.name="testpipe3" --detect.project.version.name="1.0" \
   --detect.project.codelocation.unmap=true \
   --detect.report.timeout=36000 --blackduck.timeout=36000 \
   --detect.yarn.prod.only=true --detect.npm.include.dev.dependencies=false \
   --detect.notices.report=true 


